const TorBoxConstants = {
  API_BASE: "https://api.torbox.app",
  STATES: {
    PENDING: "pending",
    CHECKING: "checking",
    CACHED: "cached",
    NOT_CACHED: "not_cached",
    UNSUPPORTED: "unsupported",
    ERROR: "error"
  },
  MESSAGES: {
    GET_HOSTERS: "GET_HOSTERS",
    CHECK_CACHE: "CHECK_CACHE",
    DOWNLOAD_CACHED: "DOWNLOAD_CACHED",
    GET_API_KEY: "GET_API_KEY",
    SET_API_KEY: "SET_API_KEY",
    TEST_AUTH: "TEST_AUTH",
    GET_SETTINGS: "GET_SETTINGS",
    SET_SETTINGS: "SET_SETTINGS",
    CREATE_WEBDL: "CREATE_WEBDL",
    CREATE_USENET: "CREATE_USENET",
    GET_ACTIVE_DOWNLOADS: "GET_ACTIVE_DOWNLOADS"
  },
  DEFAULT_SETTINGS: {
    autoScan: true,
    showUncached: true,
    showErrors: false
  },
  DEFAULT_HOSTERS: [
    "1fichier.com",
    "alfafile.net",
    "anonfiles.com",
    "bayfiles.com",
    "bunkr.is",
    "bunkr.ru",
    "bunkr.site",
    "bunkr.la",
    "clicknupload.cc",
    "clicknupload.to",
    "ddownload.com",
    "doodstream.com",
    "dood.watch",
    "dood.to",
    "dood.so",
    "dood.la",
    "drop.download",
    "easybytez.com",
    "fastbit.cc",
    "fikper.com",
    "filefactory.com",
    "filejoker.net",
    "filenext.com",
    "flashx.tv",
    "florenfile.com",
    "flybit.vip",
    "gofile.io",
    "goload.io",
    "hexupload.net",
    "hotlink.cc",
    "hulkshare.com",
    "icybox.com",
    "isra.cloud",
    "israel.tv",
    "keep2share.cc",
    "k2s.cc",
    "katfile.com",
    "krakenfiles.com",
    "mediafire.com",
    "mega.nz",
    "mega.co.nz",
    "mixdrop.co",
    "mixdrop.to",
    "mixdrop.ch",
    "nelion.me",
    "nitroflare.com",
    "nitro.download",
    "oboom.com",
    "openload.co",
    "pixeldrain.com",
    "prefiles.com",
    "qiwi.gg",
    "rapidgator.net",
    "rosefile.net",
    "send.cm",
    "solidfiles.com",
    "streamtape.com",
    "streamtape.cc",
    "streamtape.to",
    "takefile.link",
    "tezfiles.com",
    "turbobit.net",
    "ubiqfile.com",
    "unibytes.com",
    "upload.ee",
    "uploaded.net",
    "ul.to",
    "upstore.net",
    "uptobox.com",
    "uptobox.fr",
    "vidoza.net",
    "vipr.im",
    "voe.sx",
    "wipfiles.net",
    "worldbytez.com",
    "wupfile.com",
    "zippyshare.com"
  ]
};

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = TorBoxConstants;
} else if (typeof window !== 'undefined') {
  window.TorBoxConstants = TorBoxConstants;
}
