/**
 * TorBox Constants & Default Configurations
 */
const TorBoxConstants = {
  API_BASE: "https://api.torbox.app",
  
  STATES: {
    PENDING: "pending",
    CHECKING: "checking",
    CACHED: "cached",
    NOT_CACHED: "not_cached",
    UNSUPPORTED: "unsupported",
    ERROR: "error"
  },
  
  MESSAGES: {
    GET_HOSTERS: "GET_HOSTERS",
    CHECK_CACHE: "CHECK_CACHE",
    DOWNLOAD_CACHED: "DOWNLOAD_CACHED",
    START_NATIVE_DOWNLOAD: "START_NATIVE_DOWNLOAD",
    GET_API_KEY: "GET_API_KEY",
    SET_API_KEY: "SET_API_KEY",
    TEST_AUTH: "TEST_AUTH",
    GET_USER_INFO: "GET_USER_INFO",
    GET_USER_STATS: "GET_USER_STATS",
    GET_SETTINGS: "GET_SETTINGS",
    SET_SETTINGS: "SET_SETTINGS",
    CREATE_WEBDL: "CREATE_WEBDL",
    CREATE_USENET: "CREATE_USENET",
    CREATE_TORRENT: "CREATE_TORRENT",
    GET_ACTIVE_DOWNLOADS: "GET_ACTIVE_DOWNLOADS",
    REQUEST_DOWNLOAD_BY_ID: "REQUEST_DOWNLOAD_BY_ID",
    CONTROL_DOWNLOAD: "CONTROL_DOWNLOAD",
    UPDATE_BADGE: "UPDATE_BADGE",
    GET_PAGE_LINKS: "GET_PAGE_LINKS",
    SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
    MAGNET_TO_FILE: "MAGNET_TO_FILE",
    GET_TORRENT_INFO: "GET_TORRENT_INFO",
    START_DEVICE_AUTH: "START_DEVICE_AUTH",
    CHECK_DEVICE_AUTH_TOKEN: "CHECK_DEVICE_AUTH_TOKEN",
    SEND_TO_CLOUD: "SEND_TO_CLOUD",
    GET_CLOUD_INTEGRATIONS: "GET_CLOUD_INTEGRATIONS"
  },

  CLOUD_PROVIDERS: {
    googledrive: { name: "Google Drive", icon: "📁" },
    onedrive: { name: "OneDrive", icon: "☁️" },
    dropbox: { name: "Dropbox", icon: "📦" },
    gofile: { name: "Gofile", icon: "🚀" },
    "1fichier": { name: "1Fichier", icon: "🗄️" },
    pixeldrain: { name: "Pixeldrain", icon: "💾" }
  },

  PLAN_TIERS: {
    0: { name: "Free", badge: "FREE", color: "#94a3b8" },
    1: { name: "Essential", badge: "ESSENTIAL", color: "#3b82f6" },
    2: { name: "Pro", badge: "PRO", color: "#10b981" },
    3: { name: "Standard", badge: "STANDARD", color: "#8b5cf6" }
  },

  DEFAULT_SETTINGS: {
    autoScan: true,
    scanTextLinks: true,
    showFloatingDock: true,
    skipSaveDialog: true, // Skip the save dialog window when downloading
    downloadEngine: "idm", // "idm" (trigger via page for IDM/FDM interception) or "browser" (chrome.downloads API)
    autoDownloadCached: false,
    notificationsEnabled: true,
    backgroundCompletionAlerts: true,
    customExcludedDomains: []
  },

  DEFAULT_HOSTERS: [
    "1024tera.com",
    "1024terabox.com",
    "123684.com",
    "123pan.com",
    "1fichier.com",
    "4archive.org",
    "4chan.org",
    "4chanarchives.com",
    "4funbox.com",
    "4s.io",
    "4shared-china.com",
    "4shared.com",
    "alfafile.net",
    "annas-archive.gd",
    "annas-archive.gl",
    "annas-archive.in",
    "annas-archive.li",
    "annas-archive.org",
    "annas-archive.pm",
    "annas-archive.se",
    "anonfiles.com",
    "apkadmin.com",
    "archive.org",
    "bayfiles.com",
    "beta.webshare.cz",
    "bsky.app",
    "bunkr.cr",
    "bunkr.fi",
    "bunkr.is",
    "bunkr.la",
    "bunkr.ph",
    "bunkr.pk",
    "bunkr.red",
    "bunkr.ru",
    "bunkr.si",
    "bunkr.site",
    "bunkrrr.org",
    "buzzheavier.com",
    "castbox.fm",
    "catbox.moe",
    "cccy.su",
    "cdn.discordapp.com",
    "clickndownload.cfd",
    "clicknupload.cc",
    "clicknupload.click",
    "clicknupload.club",
    "clicknupload.co",
    "clicknupload.com",
    "clicknupload.download",
    "clicknupload.link",
    "clicknupload.me",
    "clicknupload.name",
    "clicknupload.one",
    "clicknupload.online",
    "clicknupload.org",
    "clicknupload.red",
    "clicknupload.site",
    "clicknupload.space",
    "clicknupload.to",
    "clicknupload.vip",
    "clicknupload.xyz",
    "coomer.party",
    "coomer.st",
    "coomer.su",
    "cyberdrop.cr",
    "dailyuploads.cc",
    "dailyuploads.im",
    "dailyuploads.net",
    "darkibox.com",
    "datanodes.to",
    "datavaults.co",
    "ddl.to",
    "ddownload.com",
    "depositfiles.com.ua",
    "deviantart.com",
    "disk.yandex.com",
    "disk.yandex.net",
    "disk.yandex.ru",
    "dlbit.net",
    "dood.la",
    "dood.so",
    "dood.to",
    "dood.watch",
    "doodstream.com",
    "drive.google.com",
    "drive.usercontent.google.com",
    "driveseed.org",
    "drop.download",
    "dropapk.com",
    "dropapk.to",
    "dropbox.com",
    "dubox.com",
    "easybytez.com",
    "e-hentai.org",
    "en.webshare.cz",
    "eporner.com",
    "es.scribd.com",
    "extmatrix.com",
    "fansly.com",
    "fastbit.cc",
    "fastclick.to",
    "fayloobmennik.com",
    "fikper.com",
    "filebee.xyz",
    "filecrypt.cc",
    "filecrypt.co",
    "filedeluxe.com",
    "filefactory.com",
    "filejoker.net",
    "filemaster.ru",
    "filenext.com",
    "filepress.cloud",
    "filepress.live",
    "filepress.shop",
    "filepress.today",
    "fileq.net",
    "filer.net",
    "files.vc",
    "filespace.com",
    "filestore.me",
    "filhost.ru",
    "flashx.tv",
    "florenfile.com",
    "flybit.vip",
    "forum.flacmania.ru",
    "fuckingfast.co",
    "furry34.com",
    "gelbooru.com",
    "gibibox.com",
    "github.com",
    "gofile.io",
    "goload.io",
    "googleusercontent.com",
    "hentai-foundry.com",
    "hexload.com",
    "hexupload.com",
    "hexupload.net",
    "hitf.cc",
    "hitfile.net",
    "hitomi.la",
    "hotlink.cc",
    "hotshare.biz",
    "htfl.net",
    "hubcloud.cx",
    "hubcloud.foo",
    "hubdrive.space",
    "hubdrive.tips",
    "hulkshare.com",
    "icybox.com",
    "ifolder.com.ua",
    "imgbb.com",
    "imgur.com",
    "isra.cloud",
    "isracloud.com",
    "israel.tv",
    "k2s.cc",
    "katfile.biz",
    "katfile.cloud",
    "katfile.com",
    "katfile.online",
    "keep2share.cc",
    "kemono.cr",
    "kemono.party",
    "kemono.su",
    "kilofile.com",
    "koofr.eu",
    "krakenfiles.com",
    "m1xdrop.com",
    "mangadex.org",
    "mdbekjwqa.pw",
    "mdfx9dc8n.net",
    "mdy48tn97.com",
    "mdzsmutpcvykb.net",
    "mediafire.com",
    "mega.co.nz",
    "mega.io",
    "mega.nz",
    "megadb.net",
    "megadb.xyz",
    "megaup.net",
    "mirrobox.com",
    "mixdroop.bz",
    "mixdrop.ag",
    "mixdrop.bz",
    "mixdrop.ch",
    "mixdrop.club",
    "mixdrop.co",
    "mixdrop.is",
    "mixdrop.ms",
    "mixdrop.my",
    "mixdrop.ps",
    "mixdrop.si",
    "mixdrop.sn",
    "mixdrop.sx",
    "mixdrop.to",
    "mixdrop.vc",
    "mixloads.com",
    "mypikpak.com",
    "nelion.me",
    "nexusmods.com",
    "nhentai.net",
    "nitro.download",
    "nitroflare.com",
    "oboom.com",
    "openload.co",
    "pan.baidu.com",
    "pillowcase.su",
    "pillows.su",
    "pixeldrain.com",
    "pixeldrain.dev",
    "prefiles.com",
    "qiwi.gg",
    "rapidfile.tk",
    "rapidgator.net",
    "rapidrar.com",
    "rapidrar.online",
    "rapidrar.xyz",
    "rg.to",
    "rosefile.net",
    "rule34.xxx",
    "salefiles.com",
    "scribd.com",
    "send.cm",
    "send.now",
    "sendit.cloud",
    "sendspace.com",
    "sharemods.com",
    "sharemods.org",
    "shavetape.cash",
    "sibit.net",
    "solidfiles.com",
    "strcloud.club",
    "strcloud.in",
    "strcloud.link",
    "streamadblocker.xyz",
    "streamta.pe",
    "streamta.site",
    "streamtape.cc",
    "streamtape.com",
    "streamtape.net",
    "streamtape.to",
    "streamtape.xyz",
    "strtape.cloud",
    "strtape.tech",
    "strtpe.link",
    "swisstransfer.com",
    "t.me",
    "takefile.link",
    "tapeadvertisement.com",
    "tapecontent.net",
    "terabox.app",
    "terabox.com",
    "teraboxapp.com",
    "terabytez.org",
    "tezfiles.com",
    "torbobit.net",
    "tourbit.com",
    "transfer.it",
    "transfernow.net",
    "trbt.cc",
    "turb.cc",
    "turb.to",
    "turbabit.net",
    "turbo-bit.pw",
    "turbo.to",
    "turbobbit.com",
    "turbobeet.net",
    "turbobi.pw",
    "turbobif.com",
    "turbobit.cc",
    "turbobit.cloud",
    "turbobit.com",
    "turbobit.live",
    "turbobit.net",
    "turbobit.online",
    "turbobit.pw",
    "turbobit.ru",
    "turbobit5.net",
    "turbobita.net",
    "turbobite.net",
    "turbobith.net",
    "turbobitt.net",
    "turbobiyt.net",
    "turbobyt.com",
    "turbobyte.net",
    "turboget.net",
    "turboot.ru",
    "turo-bit.net",
    "tusfiles.com",
    "tusfiles.net",
    "twobit.ru",
    "ubiqfile.com",
    "ul.to",
    "unibytes.com",
    "upload.ee",
    "uploaded.net",
    "uploadhaven.com",
    "uploady.io",
    "upstore.net",
    "uptobox.com",
    "uptobox.fr",
    "userscloud.com",
    "usersfiles.com",
    "vik1ngfile.site",
    "vikingf1le.us.to",
    "vikingfile.com",
    "vidoza.net",
    "vipr.im",
    "voe.sx",
    "watchadsontape.com",
    "wayupload.com",
    "webshare.cz",
    "webtoons.com",
    "wipfiles.net",
    "worldbytez.com",
    "worldbytez.net",
    "worldbytez.xyz",
    "wupfile.com",
    "xrfiles.ru",
    "zippyshare.com"
  ],

  DEFAULT_STREAMS: [
    "4tube.com",
    "abcnews.go.com",
    "acast.com",
    "aparat.com",
    "audioboom.com",
    "audiomack.com",
    "baishi.xiaodutv.com",
    "bbc.co.uk",
    "beeg.com",
    "bilibili.com",
    "cc.com",
    "chilloutzone.net",
    "clips.twitch.tv",
    "comedycentral.com",
    "dailymail.co.uk",
    "dailymotion.com",
    "dctp.tv",
    "drtuber.com",
    "ebaumsworld.com",
    "facebook.com",
    "formula1.com",
    "foxnews.com",
    "gamestar.de",
    "go.twitch.tv",
    "hanime.tv",
    "idnes.cz",
    "instagram.com",
    "izlesene.com",
    "jamendo.com",
    "khanacademy.org",
    "kick.com",
    "kickstarter.com",
    "lcp.fr",
    "loom.com",
    "m.twitch.tv",
    "nbcsports.com",
    "nfl.com",
    "nicovideo.jp",
    "nytimes.com",
    "ok.ru",
    "panopto.com",
    "pinimg.com",
    "pinterest.com",
    "player.twitch.tv",
    "pornhub.com",
    "pornhub.net",
    "pornhub.org",
    "pornhubpremium.com",
    "reddit.com",
    "redgifs.com",
    "redtube.com",
    "rutube.ru",
    "snapchat.com",
    "soundcloud.com",
    "spankbang.com",
    "steamcommunity.com",
    "steampowered.com",
    "streamable.com",
    "stripchat.com",
    "sunporno.com",
    "t.co",
    "tiktok.com",
    "tlc.com",
    "tumblr.com",
    "twitch.tv",
    "twitter.com",
    "v.baidu.com",
    "v.xiaodutv.com",
    "video.yandex.ru",
    "vimeo.com",
    "vk.com",
    "www.camdemy.com",
    "x.com",
    "xhamster.com",
    "xhamster.desi",
    "xhamster.one",
    "xhday.com",
    "xhms.pro",
    "xhslink.com",
    "xhvid.com",
    "xiaohongshu.com",
    "xnxx.com",
    "xvideos.com",
    "xxxymovies.com",
    "yandex.com",
    "yandex.ru",
    "youjizz.com",
    "youporn.com"
  ]
};

// Export for module or browser window usage
if (typeof module !== "undefined" && module.exports) {
  module.exports = TorBoxConstants;
} else if (typeof window !== "undefined") {
  window.TorBoxConstants = TorBoxConstants;
} else if (typeof globalThis !== "undefined") {
  globalThis.TorBoxConstants = TorBoxConstants;
}
